### ISSUE TITLE
TypeError: Class extends value undefined is not a function or null

### ISSUE THREAD

**Issue by robinelvin** [meuschke/relay-testing-utils#4]
I get the following error when trying to use this module in my tests:

    TypeError: Class extends value undefined is not a function or null
      
      at Object.relayMock (node_modules/relay-testing-utils/build/relay-mock.js:9:31)
      at Object.<anonymous> (src/components/__mocks__/react-relay.js:6:49)
      at Object.<anonymous> (src/components/filter.tsx:10:2)
      at Object.<anonymous> (src/components/__tests__/filter.test.tsx:2:1)

**Comment by robinelvin** [comment]
Ah, I've just realised that I'm using Relay Modern....

**Comment by meuschke** [comment]
@robinelvin Yes its not compatible with modern. Your more then welcome to change it and make a PR. In the moment I don´t have the time to fix it.
